name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install stable Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Remove pip cache
        run: rm -rf /home/runner/.cache/pip

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Python dependencies (with setuptools-rust)
        run: |
          pip install --upgrade -r requirements.txt
          pip install setuptools-rust wheel

      - name: Install pytest-django
        run: pip install pytest-django

      - name: Export PYTHONPATH
        run: echo "PYTHONPATH=\${PYTHONPATH}:${{ github.workspace }}" >> $GITHUB_ENV

      - name: Check Python Path
        run: python -c "import os; print('PYTHONPATH:', os.environ.get('PYTHONPATH'))"

      - name: Run tests
        run: pytest 
