name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Export PYTHONPATH
        run: echo "PYTHONPATH=\${PYTHONPATH}:${{ github.workspace }}" >> $GITHUB_ENV

      - name: Check Python Path
        run: python -c "import os; print('PYTHONPATH:', os.environ.get('PYTHONPATH'))"

      - name: Run tests
        run: pytest 