jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies via pip
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest 